[package]
name = "rust-cli-spotify"
version = "0.1.0"
authors = ["Dev Menon"]
edition = "2018"

[dependencies]
structopt = "0.3.22"
rand = "0.8.4"
serde_json = "1.0.59"
rspotify = { version = "0.10.0", features=["blocking"]}
futures = "0.3"
